### PR TITLE
Remove empty query string from base path when params are not passed.

### PR DESCRIPTION
**Pull request by e-e-e**
This is a proposed solution to this issue: https://github.com/rchipka/node-osmosis/issues/187.

I added a test which highlights the issue too.

Let me know your thoughts.

### CODE REVIEW

**Comment by e-e-e** [comment]
Hey @rchipka, is there any chance of merging this pr. This issue is currently causing us a lot of issues.

**Comment by rchipka** [comment]
Couldn't you fix this by passing null or undefined instead of an empty object?

I would think that an empty query string object appending a "?" would be considered expected behavior.

If you pass an empty object it makes sense to me that you're specifying a query string without parameters.

Whereas if you pass null or undefined, you're explicitly saying that there isn't a query string.

**Comment by rchipka** [comment]
If it is the case that [this.params](https://github.com/rchipka/node-osmosis/blob/master/lib/commands/get.js#L33) is not null or undefined by default (which it should be), then I think the best solution would be to fix it from there instead.

**Comment by e-e-e** [comment]
@rchipka this.params is not undefined by default. My initial thoughts were the same as you express, but to be honest I could not discern in the code where default params were being set, and where it is being modified. I figured the safest way was to sanitize it before the request. If you could point me to the area in the code where this.params is being initialised - i am happy to modify. Although if this.params is currently an object, changing it to undefined could also break any instance it is assigned values - could you also point me to where is it assigned?

**Comment by rchipka** [comment]
Looks like it's being set [here](https://github.com/rchipka/node-osmosis/blob/master/lib/Command.js#L348).

We should probably check [here](https://github.com/rchipka/node-osmosis/blob/master/lib/Command.js#L343) that `params` isn't null or undefined.

This way we don't loop each `key` in the null or undefined `params` object, and we don't end up setting `url.params` to `url.query` (which will always be an object).

**Comment by rchipka** [comment]
If you do provide a fix, you shouldn't need the empty object check.

Just a strict comparison for null or undefined.

Alternatively, we could be more specific with `(params instanceof Object && params !== null)`

Once you make the changes, make sure your tests still pass and I'll merge this in.

**Comment by e-e-e** [comment]
Thanks for the pointers - really helpful - and sorry for the delay - I have been chasing my tail this week.
I updated the PR to reflect your comments. Unfortunately the empty object check is still needed as you still need to assign the query object if there are values present. It failed tests without it.

Let me know your thoughts - this should resolve the issue.

**Pull request merged**
